version: '3'
services:
  web:
    image: nginx:latest
    build:
      context: './docker/nginx/'
      dockerfile: Dockerfile
    volumes: [
      './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf',
      '.:/var/www/html'
    ]

  php:
    image: php:7.2-fpm
    build:
      context: './docker/php/'
      dockerfile: Dockerfile
    volumes: [
      './docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf',
      '.:/var/www/html'
    ]

  db:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=symfony
    - MYSQL_USER=symfony
    - MYSQL_PASSWORD=password