version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
  redis:
    build: ./docker/redis
    ports: ['6379:6379']
    volumes:
      - ./data/redis:/data:cached
  php:
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - mysql
      - redis
    volumes:
      - ./symfony/:/var/www/symfony:cached
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./symfony/:/var/www/symfony:cached
  varnish:
    build: ./docker/varnish
    ports: ['8080:80']
    links:
      - nginx