version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
  redis:
    build: ./docker/redis
    volumes:
      - ./data/redis:/data:cached
  php:
    build: ./docker/php
    links:
      - mysql
      - redis
    volumes:
      - ./symfony/:/var/www/symfony:cached
  nginx:
    build: ./docker/nginx
    links:
      - php
    volumes:
      - ./symfony/:/var/www/symfony:cached
  varnish:
    build: ./docker/varnish
    links:
      - nginx